version: '3.8'

services:
  selfhostedmcp:
    image: ${DOCKER_USERNAME}/selfhostedmcp:latest
    # Alternatively, build locally:
    # build: .
    ports:
      - "80:5173"  # Map container port 5173 to host port 80
    restart: unless-stopped
